class KXCelt : KCCreature
{
	int user_celt;
	default
	{
		//$Category Monsters
		//$Title Celt
		Health 3000;
		Radius 24;
		Height 64;
		Mass 1000;
		Speed 18;
		PainChance 20;
		Monster;
		Obituary "%o was frozen to death by Celt";
		HitObituary "%o was frozen to death by Celt";
		Bloodcolor "7c7c98";
		Species "Celt";
		+DONTHARMSPECIES;
		+NOTARGET;
		+FLOORCLIP;
		//+MISSILEMORE;
		+DONTHARMCLASS;
		Tag "Celt";
		SeeSound "Celt/see";
		PainSound "Celt/pain";
		DeathSound "Celt/death2";
		ActiveSound "Celt/idle";
		
		RadiusDamageFactor 0.75;
		DamageFactor "Holy", 3.25;
		DamageFactor "Magic", 0.334;
		DamageFactor "PSI", 3;
		DamageFactor "Ice", 0.125;
		DamageFactor "Fire", 0.25;
		DamageFactor "Lightning", 1.75;
		DamageFactor "Explosive", 0.75;
		Damagefactor "IncarnateGlare", 5;
		MissileChanceMult 0.5;
	}
	
	void A_CeltIceSpread(int type)
	{
		double spawnheight = 28;
		if (type <= 0)
		{
			double ang = angle;
			double slope = AimLineAttack(ang, MISSILERANGE);
			if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self))
			{
				for (int i = 0; i < 15; i++)
				{
					A_SpawnProjectile("CeltIceMiniShot",spawnheight,0,(ang+random(-10,10)),CMF_ABSOLUTEPITCH|CMF_ABSOLUTEANGLE,(slope+random(-5,5)));
				}
			}
			for (int i = 0; i < 15; i++)
			{
				A_SpawnProjectile("CeltIceMiniShot",spawnheight,0,(ang+random(-10,10)),CMF_ABSOLUTEPITCH|CMF_ABSOLUTEANGLE,(slope+random(-5,5)));
			}
		}
	}
	
	void A_CeltDeath()
	{
		if (level.GetChecksum() == 'a53ae580a4af2b5d0b0893f86914781e')
		{
			int num;
			ThinkerIterator celts = ThinkerIterator.Create("KXCelt");
			KXCelt cetcnt;
			while (cetcnt = KXCelt(celts.Next()))
			{
				if (cetcnt.health > 0) num++;
			}
			
			//Console.Printf("num: %d", num);
			if (num <= 0)
			{
				int rand = random(1,3);
				vector3 artspot = (-2928, -2016, 0);
				if (rand <= 1) artspot = (-2928, -2016, 0);
				if (rand == 2) artspot = (-1216, -1216, 0);
				if (rand >= 3) artspot = (2400, 2304, 0);
				actor mo = Spawn("IceWeaselArtifact", artspot, NO_REPLACE);
			}
		}
	}
	
	void A_CeltDefaultIceParticle()
	{
		A_SpawnItemEx("KXCeltIceParticle", frandom(24, 32), 0, 4, 0, 0, (frandom(20,35)*0.1), frandom(0,360), 128);
	}
	
	void A_CeltChargeIceParticles()
	{
		if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) 
		{
			A_SetTics(0); 
		}
		else
		{
			A_CeltDefaultIceParticle();
		}
	}
	
	States
	{
		Spawn:
			CELT AB 10 A_Look();
			Loop;
		See:
			TNT1 A 0 { user_celt = 0; }
			CELT AABBCCDD 3 
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { bAVOIDMELEE = true; }
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(2); }
				A_KCChase("Melee","Missile",0,1,3,1,1);
				
				if (A_CheckRange(1024,"Null")) { } else 
				{
					if (GetCVar("kc_gfxeffectlevel") == 0) 
					{
						A_CeltDefaultIceParticle();
						A_CeltDefaultIceParticle();
						A_CeltDefaultIceParticle();
					} 
				}
			}
			Loop;
		Melee:
		Missile:
			TNT1 A 0 A_Jump(128,"Spread","AnotherSpread");
			TNT1 A 0 A_Jump(128,"Ring", "DiamondDust");
			TNT1 A 0 A_Jump(128,"Clone");
		Spread:
			CELT EF 8 Bright 
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT G 0 Bright 
			{
				A_CeltIceSpread(0);
			}
			CELT H 3 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(1); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(2); }
			}
			CELT H 0 A_Jump(128,1);
			Goto See;
			CELT IJ 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT K 0 Bright 
			{
				A_CeltIceSpread(0);
			}
			CELT L 3
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(1); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(2); }
			}
			CELT L 0 A_Jump(64,"Ring");
			Goto See;
		AnotherSpread:
			CELT MN 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT O 0 Bright 
			{
				double angint = 15;
				double shotheight = 28;
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*5),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*4),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*3),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*2),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*1),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*0),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*-1),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*-2),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*-3),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*-4),0);
				A_SpawnProjectile("CeltIceBigShot",shotheight,0,(angint*-5),0);
			}
			CELT OP 4 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(2); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(3); }
			}
			Goto See;
		Ring:
			TNT1 A 0 { user_celt = 0; }
			CELT MN 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			Goto RingLooping;
		RingLooping:
			TNT1 A 0 A_SpawnProjectile("CeltIceMiniShot2",28,0,user_celt,CMF_ABSOLUTEANGLE);
			TNT1 A 0 
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { user_celt += 2; }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { user_celt += 4; }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { user_celt += 6; }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { user_celt += 8; }
				else { user_celt += 10; }
			}
			TNT1 A 0 A_JumpIf(user_celt >= 360, 1);
			Loop;
			TNT1 A 0 { user_celt = 0; }
			CELT OP 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			Goto See;
		DiamondDust: 
			CELT MMMM 1 A_CeltDefaultIceParticle();
			CELT MMMM 1 A_CeltChargeIceParticles();
			CELT A 0 Bright A_FaceTarget();
			CELT MMMM 1 A_CeltDefaultIceParticle();
			CELT MMMM 1 A_CeltChargeIceParticles();
			CELT A 0 Bright A_FaceTarget();
			CELT NNNN 1 A_CeltDefaultIceParticle();
			CELT NNNN 1 A_CeltChargeIceParticles();
			CELT O 4 Bright 
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(2); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(3); }
				A_SpawnProjectile("CeltDiamondDust",28,0,0,0);
			}
			CELT P 4 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(2); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(3); }
			}
			Goto See;
		Clone:
			CELT QQQQQ 1 A_CeltDefaultIceParticle();
			CELT QQQQQ 1 A_CeltChargeIceParticles();
			CELT Q 0 
			{
				actor TraceShot;
				TraceShot = A_SpawnProjectile("CeltIceCloneSpawner",2,0,90,2,0);
				if (TraceShot)
				{
					if (master) TraceShot.master = master;
								 else TraceShot.master = self;
				}
				TraceShot = A_SpawnProjectile("CeltIceCloneSpawner",2,0,-90,2,0);
				if (TraceShot)
				{
					if (master) TraceShot.master = master;
								 else TraceShot.master = self;
				}
			}
			CELT QQQQQQQQQQQQQQQQQQQQ 1 A_CeltDefaultIceParticle();
			CELT QQQQQQQQQQQQQQQQQQQQ 1 A_CeltChargeIceParticles();
			Goto See;
		Pain:
			#### # 0 A_TimeFreezeCheckPain();
			CELT Q 2;
			CELT Q 2 A_KCPain();
			Goto See;
		Death:
			CELT R 10 Bright 
			{
				A_KillChildren("Massacre");
				A_Scream();
			}
			CELT STUV 10 Bright
			{
				A_KillChildren("Massacre");
			}
			TNT1 A 0
			{
				A_KillChildren("Massacre");
				A_StartSound("Celt/CometDeath",CHAN_7,CHANF_DEFAULT,1.0,ATTN_NONE,1.0);
				if (level.GetChecksum() == 'a53ae580a4af2b5d0b0893f86914781e')
				{
					A_StartSound("Celt/CometDeath",8,CHANF_DEFAULT,1.0,ATTN_NONE,0.9);
					A_StartSound("Celt/CometDeath",9,CHANF_DEFAULT,1.0,ATTN_NONE,1.1);
				}
				else
				{
					A_SpawnItemEx("CeltBody",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_NOCHECKPOSITION);
				}
			}
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("KXCeltIceParticle2",0,0,5,frandom(-15,15),frandom(-15,15),frandom(5,15),random(1,360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 1 Bright 
			{
				A_KillChildren("Massacre");
				A_SpawnItemEx("CeltRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			}
			CELT U 0 Bright 
			{
				A_NoBlocking();
				A_CeltDeath();
			}
			TNT1 A -1 Bright;
			Stop;
	}
}

class CeltBody : KCBaseZSC
{
	default
	{
		Radius 0;
		Height 0;
		Speed 0;
		+ClientSideOnly;
		+NoBlockMap;
		Translation "0:255=%[0.00,0.00,1.84]:[1.24,1.24,2.00]";
	}
	
	States
	{
		Spawn:
			CELT WXY 5 Bright;
			CELT Z -1 Bright;
			Stop;
	}
}

class CeltIceBigShot : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 3;
		Height 3;
		Speed 20;
		Damage 8;
		Projectile;
		RenderStyle "Add";
		DamageType "Ice";
		SeeSound "Celt/IceShot";
		DeathSound "Celt/IceHit";
		Translation "0:255=%[0.00,0.00,1.84]:[1.24,1.24,2.00]";
		Decal "RevenantScorch";
	}
	
	States
	{
		Spawn:
			IBAL AABB 2 Bright A_SpawnItemEx("CeltIceBigShotTrail",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
			Loop;
		Death:
			IBAL AAAAAAAAAA 0 A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			IBAL DEFGHI 4 Bright;
			Stop;
	}
}

class CeltIceBigShotTrail : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 1;
		Height 1;
		Speed 0;
		Damage 0;
		PROJECTILE;
		RenderStyle "Add";
		DamageType "Ice";
		Translation "0:255=%[0.00,0.00,1.84]:[1.24,1.24,2.00]";
		+ClientSideOnly;
		+Randomize;
		Alpha 0.9;
	}
	
	States
	{
		Spawn:
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			Loop;
	}
}

class CeltIceMiniShot : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 3;
		Height 3;
		Speed 35;
		Damage 3;
		Projectile;
		RenderStyle "Add";
		DamageType "Ice";
		SeeSound "Celt/IceShot";
		DeathSound "Celt/IceHit";
	}
	
	States
	{
		Spawn:
			IPRJ AAABBBCCC 1 Bright A_SpawnItemEx("CeltIceMiniShotTrail",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
			Loop;
		Death:
			IPRJ AAA 0 A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-4,4),frandom(-4,4),frandom(-4,4),random(1,360));
			IPRJ DEFGH 3 Bright;
			Stop;
	}
}

class CeltIceMiniShot2 : CeltIceMiniShot
{
	default
	{
		Tag "Ice Shard";
		Speed 12;
	}
}

class CeltIceMiniShotTrail : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 1;
		Height 1;
		Speed 0;
		Damage 0;
		PROJECTILE;
		RenderStyle "Add";
		DamageType "Ice";
		+ClientSideOnly;
		+Randomize;
		Alpha 1.0;
	}
	States
	{
		Spawn:
			IPRJ AAAABBBBCCCC 1 Bright A_FadeOut(0.07);
			Stop;
	}
}

class CeltDiamondDust : KCProjectile
{
	default
	{
		Tag "Diamond Dust";
		Radius 13;
		Height 8;
		Speed 25;
		Damage 0;
		Projectile;
		SeeSound "CELT/comet";
		Translation "0:255=%[0.00,0.00,2.00]:[2.00,2.00,2.00]";
		RenderStyle "Add";
		Projectile;
		DamageType "Ice";
		Decal "RevenantScorch";
	}
	
	States
	{
		Spawn:
			ICOM AAAABBBBCCCC 1 Bright A_SpawnItemEx("CeltDiamondDustTail", 0, 0, 0, 0, 0, 0, 0, 128);
			Loop;
		Death:
			ICOM A 0 A_StartSound("Celt/CometDeath",CHAN_AUTO,CHANF_DEFAULT,1.0,ATTN_NONE);
			ICOM A 0 Bright A_Explode(256,256,0);
			ICOM AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			ICOM DDDDEEEEFFFFGGGGHHHHIIII 1 Bright A_SpawnItemEx("CeltRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			Stop;
	}
}

class CeltDiamondDustTail : KCProjectile
{
	default
	{
		Tag "Diamond Dust";
		Radius 1;
		Height 1;
		Speed 0;
		Damage 0;
		RenderStyle "Add";
		DamageType "Ice";
		Projectile;
		+DontSplash;
		+ClientSideOnly;
	}
	
	States
	{
		Spawn:
			TNT1 A 2;
			IRTB ABCDEFGHI 1 Bright;
			Stop;
	}
}

class CeltRealDiamondDust : KCProjectile
{
	default
	{
		Tag "Diamond Dust";
		Radius 15;
		Height 8;
		Speed 20;
		Damage 2;
		Projectile;
		+Ripper;
		BounceType "Hexen";
		Obituary "%o was frozen by Celt.";
		DamageType "Ice";
	}
	
	States
	{
		Spawn: 
			IRME ABCDEFGHIJKLMNS 2 Bright;
			IRME S 1 A_FadeOut(0.01);
			Wait;
	}
}

class CeltIceCloneSpawner : PlasmaBallNew
{
	default
	{
		RenderStyle "Normal";
		Radius 24;
		Height 1;
		Speed 9;
		BounceType "Hexen";
		Damage 0;
		SeeSound "";
		DeathSound "";
		DamageType "Ice";
		Translation "0:255=%[0.00,0.00,2.00]:[2.00,2.00,2.00]";
	}
	
	States
	{
		Spawn:
			CELT ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ 1 A_SpawnItemEx("KXCeltIceParticle", Random(24, 32), 0, 4, 0, 0, (Random(20, 35)*0.1), Random(0, 360), 128);
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_StartSound("misc/freeze",CHAN_AUTO,CHANF_DEFAULT,1.0);
			Goto Death;
		Death:
			CELT YYYYYYXXXXXXWWWWWWVVVVVVUUUUUUTTTTTTSSSSSSRRRRRR 1 A_SpawnItemEx("KXCeltIceParticle", Random(24, 32), 0, 4, 0, 0, (Random(20, 35)*0.1), Random(0, 360), 128);
			TNT1 A 0 A_StartSound("misc/freeze",CHAN_AUTO,CHANF_DEFAULT,1.0);
			TNT1 A 0 Bright 
			{
				bool spawned;
				actor mo;
				[spawned, mo] = A_SpawnItemEx("CeltIceClone",0,0,1,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_NOCHECKPOSITION);
				if (mo)
				{
					if (master) mo.master = master;
				}
			}
			Stop;
	}
}

class CeltIceClone : BaronOfHellNew
{
	default
	{
		Health 150;
		Speed 16;
		PainChance 20;
		Species "Celt";
		+DontHarmSpecies;
		-CountKill;
		-BossDeath;
		SeeSound "";
		PainSound "";
		DeathSound "misc/freeze";
		ActiveSound "";
		Obituary "%o was frozen by Celt";
		HitObituary "%o was frozen by Celt";
		BloodColor "7c7c98";
		Translation "Ice";
		Tag "Celt";

		RadiusDamageFactor 1.5;
		DamageFactor "Holy", 4.875;
		DamageFactor "Magic", 0.667;
		DamageFactor "PSI", 1.5;
		DamageFactor "Ice", 0.25;
		DamageFactor "Fire", 0.5;
		DamageFactor "Lightning", 2.5;
		DamageFactor "Explosive", 1.5;
		Damagefactor "IncarnateGlare", 12.5;
		MissileChanceMult 0.25;
	}
	
	void A_CeltIceSpread(int type)
	{
		double spawnheight = 28;
		if (type <= 0)
		{
			double ang = angle;
			double slope = AimLineAttack(ang, MISSILERANGE);
			if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self))
			{
				for (int i = 0; i < 10; i++)
				{
					A_SpawnProjectile("CeltIceMiniShot",spawnheight,0,(ang+random(-10,10)),CMF_ABSOLUTEPITCH|CMF_ABSOLUTEANGLE,(slope+random(-5,5)));
				}
			}
			for (int i = 0; i < 10; i++)
			{
				A_SpawnProjectile("CeltIceMiniShot",spawnheight,0,(ang+random(-10,10)),CMF_ABSOLUTEPITCH|CMF_ABSOLUTEANGLE,(slope+random(-5,5)));
			}
		}
	}
	
	States
	{
		Spawn:
			CELT AB 10 A_Look();
			Loop;
		See:
			CELT AABBCCDD 3 
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { bAVOIDMELEE = true; }
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(2); }
				A_KCChase("Melee","Missile",0,1,3,1,1);
			}
			Loop;
		Melee:
		Missile:
			CELT EF 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT G 0 Bright 
			{
				A_CeltIceSpread(0);
			}
			CELT GH 3 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(1); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(2); }
			}
			CELT H 0 A_Jump(128,1);
			Goto See;
			CELT IJ 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT K 0 Bright
			{
				A_CeltIceSpread(0);
			}
			CELT KL 3 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(1); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(2); }
			}
			CELT H 0 A_Jump(128,"Missile");
			Goto See;
		Pain:
			CELT Q 2;
			CELT Q 2 A_KCPain();
			Goto See;
		Ice:
		Death:
			CELT Q 5 A_IceGuyDie();
			Stop;
		Raise:
			Stop;
	}
}

class KXCeltIceParticle : KCProjectile
{
	default
	{
		Projectile;
		Damage 0;
		+NoBlockMap;
		+BloodLessImpact;
		+ClientSideOnly;
		-BloodSplatter;
		+DontSplash;
		+ForceXYBillBoard;
		Speed 0;
		Radius 1;
		Height 1;
		RenderStyle "Add";
		DamageType "Ice";
	}
	
	States
	{
		Spawn:
		Death:
			IPRJ I 1 Bright A_FadeOut(0.04);
			Loop;
	}
}

class KXCeltIceParticle2 : KCProjectile
{
	default
	{
		Projectile;
		Damage 0;
		+NoBlockMap;
		+BloodLessImpact;
		+ClientSideOnly;
		-BloodSplatter;
		+DontSplash;
		+ForceXYBillBoard;
		-NoGravity;
		Speed 0;
		Radius 1;
		Height 1;
		Scale 0.2;
		Gravity 0.8;
		RenderStyle "Add";
		DamageType "Ice";
	}
	
	States
	{
		Spawn:
			IRTB A 1 Bright;
			Loop;
		Death:
			IRTB ABCDEFGHI 1 Bright A_FadeOut(0.04);
			Wait;
	}
}

// IW
class IceWeaselAvatar : KXCelt
{
	default
	{
		//$Category Monsters
		//$Title Ice Weasel
		Health 3600; // 3000
		Scale 1.334;
		Radius 32; // 24;
		Height 96; // 64;
		Mass 90000;
		Speed 14; // 18;
		Monster;
		Obituary "%o was chilled to the bone by the Ice Weasel's incredible frozen might";
		HitObituary "%o was chilled to the bone by the Ice Weasel's incredible frozen might";
		Bloodcolor "7c7c98";
		Species "Celt";
		+NORADIUSDMG;
		+BOSS;
		+DONTHARMSPECIES;
		+NOTARGET;
		+FLOORCLIP;
		//+MISSILEMORE;
		+DONTHARMCLASS;
		+NOTELEFRAG;
		+NOINFIGHTING;
		Tag "The Ice Weasel";
		SeeSound "Celt/see2";
		PainSound "Celt/pain";
		DeathSound "IceWeasel/death";
		ActiveSound "Celt/idle";
		
		PainChance 5; // 20;
		RadiusDamageFactor 0.375;
		DamageFactor "Holy", 2.5;
		PainChance "Holy", 12.5;
		DamageFactor "Magic", 0.334;
		PainChance "Magic", 3;
		DamageFactor "PSI", 3;
		PainChance "PSI", 15;
		DamageFactor "Ice", 0.0625;
		PainChance "Ice", 0;
		DamageFactor "Fire", 0.125;
		PainChance "Fire", 1;
		DamageFactor "Lightning", 1.375;
		PainChance "Lightning", 6;
		DamageFactor "Explosive", 0.5;
		PainChance "Explosive", 3;
		Damagefactor "IncarnateGlare", 2.25;
		PainChance "IncarnateGlare", 22.5;
		Damagefactor "Translocator", 0;
		PainChance "Translocator", 0;
		MissileChanceMult 0.125;
	}
	
	void A_WeaselIceSpread(int type)
	{
		double spawnheight = 28;
		spawnheight *= 1.5;
		if (type <= 0)
		{
			double ang = angle;
			double slope = AimLineAttack(ang, MISSILERANGE);
			if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self))
			{
				for (int i = 0; i < 15; i++)
				{
					A_SpawnProjectile("WeaselIceMiniShot",spawnheight,0,(ang+random(-10,10)),CMF_ABSOLUTEPITCH|CMF_ABSOLUTEANGLE,(slope+random(-5,5)));
				}
			}
			for (int i = 0; i < 15; i++)
			{
				A_SpawnProjectile("WeaselIceMiniShot",spawnheight,0,(ang+random(-10,10)),CMF_ABSOLUTEPITCH|CMF_ABSOLUTEANGLE,(slope+random(-5,5)));
			}
		}
	}
	
	void A_WeaselDeath()
	{
		if (level.GetChecksum() == '42b68b84ff8e55f264c31e6f4cfea82d')
		{
			level.Lines[593].sidedef[0].SetTexture(1, TexMan.CheckForTexture("ZZZFACE4", TexMan.Type_Wall));
			Level.ChangeSky(TexMan.CheckForTexture("SKY3",TexMan.Type_Any),TexMan.CheckForTexture("",TexMan.Type_Any));
		}
	}
	
	states
	{
		SpawnIn:
			CELT Q 0 Bright 
			{
				A_Quake(3, 105, 0, 5120, "nosound/silent");
				A_Quake(6, 105, 0, 2560, "nosound/silent");
				A_StartSound("Celt/see2",1,CHANF_DEFAULT,1.0,ATTN_NONE,1.0);
				A_StartSound("Celt/see2",2,CHANF_DEFAULT,1.0,ATTN_NONE,0.9);
				A_StartSound("Celt/see2",3,CHANF_DEFAULT,1.0,ATTN_NONE,1.1);
				A_StartSound("Celt/see2",4,CHANF_DEFAULT,1.0,ATTN_NONE,0.8);
				A_StartSound("Celt/see2",5,CHANF_DEFAULT,1.0,ATTN_NONE,1.2);
			}
			CELT QQQQQQQQQQQQQQQQQQQQ 1 Bright 
			{
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				if (random(1,4) <= 2) A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			}
			CELT Q 1
			{
				actor playera = players[0].mo;
				if (playera) target = playera;
			}
			goto See;
		Spawn:
			CELT AB 10 A_Look();
			Loop;
		See:
			TNT1 A 0 { user_celt = 0; }
			CELT AABBCCDD 3 
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { bAVOIDMELEE = true; }
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(2); }
				A_KCChase("Melee","Missile",0,1,3,1,1);
				
				if (A_CheckRange(1024,"Null")) { } else 
				{
					if (GetCVar("kc_gfxeffectlevel") == 0) 
					{
						A_CeltDefaultIceParticle();
						A_CeltDefaultIceParticle();
						A_CeltDefaultIceParticle();
						A_CeltDefaultIceParticle();
						A_CeltDefaultIceParticle();
						A_CeltDefaultIceParticle();
					} 
				}
			}
			Loop;
		Melee:
		Missile:
			TNT1 A 0 A_Jump(128,"Spread","AnotherSpread");
			TNT1 A 0 A_Jump(128,"Ring", "DiamondDust");
			TNT1 A 0 A_Jump(128,"Clone");
		Spread:
			CELT EF 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT G 0 Bright 
			{
				A_WeaselIceSpread(0);
			}
			CELT H 3 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(1); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(2); }
			}
			CELT H 0 A_Jump(128,1);
			Goto See;
			CELT IJ 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT K 0 Bright 
			{
				A_WeaselIceSpread(0);
			}
			CELT L 3
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(1); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(2); }
			}
			CELT L 0 A_Jump(64,"Ring");
			Goto See;
		AnotherSpread:
			CELT MN 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			CELT O 0 Bright 
			{
				double angint = frandompick(8.5,11.75,11.75,15,15,15,15,15,15,18.25,18.25,21.5);
				double shotheight = 28;
				shotheight *= 1.5;
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*5),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*4),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*3),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*2),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*1),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*0),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*-1),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*-2),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*-3),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*-4),0);
				A_SpawnProjectile("WeaselIceBigShot",shotheight,0,(angint*-5),0);
			}
			CELT OP 4 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(2); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(3); }
			}
			Goto See;
		Ring:
			TNT1 A 0 { user_celt = 0; }
			CELT MN 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			Goto RingLooping;
		RingLooping:
			TNT1 A 0 
			{
				double shotheight = 28;
				shotheight *= 1.5;
				A_SpawnProjectile("WeaselIceMiniShot2",shotheight,0,user_celt,CMF_ABSOLUTEANGLE);
			}
			TNT1 A 0 
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { user_celt += 1; }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { user_celt += 2; }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { user_celt += 3; }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { user_celt += 4; }
				else { user_celt += 5; }
			}
			TNT1 A 0 A_JumpIf(user_celt >= 360, 1);
			Loop;
			TNT1 A 0 { user_celt = 0; }
			CELT OP 8 Bright
			{
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(120,2,true,self)) { A_SetTics(4); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(5); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(60,2,true,self)) { A_SetTics(6); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(30,2,true,self)) { A_SetTics(7); }
				A_FaceTarget();
			}
			Goto See;
		DiamondDust: 
			CELT MMMM 1 
			{
				A_CeltDefaultIceParticle();
				A_CeltDefaultIceParticle();
				A_FaceTarget();
			}
			CELT MMMM 1 
			{
				A_CeltChargeIceParticles();
				A_CeltChargeIceParticles();
				A_FaceTarget();
			}
			CELT MMMM 1 
			{
				A_CeltDefaultIceParticle();
				A_CeltDefaultIceParticle();
				A_FaceTarget();
			}
			CELT NNNN 1 
			{
				A_CeltChargeIceParticles();
				A_CeltChargeIceParticles();
				A_FaceTarget();
			}
			CELT NNNN 1 
			{
				A_CeltDefaultIceParticle();
				A_CeltDefaultIceParticle();
				A_FaceTarget();
			}
			CELT NNNN 1 
			{
				A_CeltChargeIceParticles();
				A_CeltChargeIceParticles();
				A_FaceTarget();
			}
			CELT O 4 Bright 
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(2); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(3); }
				
				double shotheight = 28;
				shotheight *= 1.5;
				A_SpawnProjectile("WeaselDiamondDust",shotheight,0,0,0);
			}
			CELT P 4 Bright
			{
				A_FaceTarget();
				if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(90,2,true,self)) { A_SetTics(2); }
				else if (kc_monsterlevelenabledflags && A_CheckMonsterLevel(45,2,true,self)) { A_SetTics(3); }
			}
			Goto See;
		Clone:
			CELT QQQQQ 1 
			{
				A_CeltDefaultIceParticle();
				A_CeltDefaultIceParticle();
			}
			CELT QQQQQ 1 
			{
				A_CeltChargeIceParticles();
				A_CeltChargeIceParticles();
			}
			CELT Q 0 
			{
				actor TraceShot;
				TraceShot = A_SpawnProjectile("WeaselIceCloneSpawner",2,0,90,2,0);
				if (TraceShot)
				{
					TraceShot.master = self;
				}
				TraceShot = A_SpawnProjectile("WeaselIceCloneSpawner",2,0,-90,2,0);
				if (TraceShot)
				{
					TraceShot.master = self;
				}
			}
			CELT QQQQQQQQQQQQQQQQQQQQ 1 
			{
				A_CeltDefaultIceParticle();
				A_CeltDefaultIceParticle();
			}
			CELT QQQQQQQQQQQQQQQQQQQQ 1 
			{
				A_CeltChargeIceParticles();
				A_CeltChargeIceParticles();
			}
			Goto See;
		Pain:
			#### # 0 A_TimeFreezeCheckPain();
			CELT Q 2;
			CELT Q 2 
			{
				A_KCPain(1,random(54,66),random(2,3),0,0,47.5);
			}
			Goto See;
		Pain.Electric: 
		Pain.Electricity: 
		Pain.Lightning: 
		Pain.Thunder: 
		Pain.Shock:
			#### # 0 A_TimeFreezeCheckPain();
			CELT Q 2;
			CELT Q 2 
			{
				A_KCPain(1,random(18,22),8,0,0,25);
				A_Pain();
			}
			CELT QQQQ 2;
			Goto See;
		Death:
			CELT R 0 Bright 
			{
				A_SetRenderStyle(1.0,STYLE_Add);
				A_KillChildren("Massacre");
			}
			CELT R 10 Bright 
			{
				A_Scream();
				A_KillChildren("Massacre");
			}
			CELT STUV 10 Bright
			{
				A_KillChildren("Massacre");
			}
			TNT1 A 0 
			{
				A_KillChildren("Massacre");
				A_Quake(3, 105, 0, 5120, "nosound/silent");
				A_Quake(6, 105, 0, 2560, "nosound/silent");
				A_StartSound("Celt/CometDeath",7,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(1.0,1.0));
				A_StartSound("Celt/CometDeath",8,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.96,1.04));
				A_StartSound("Celt/CometDeath",9,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.92,1.08));
				A_StartSound("Celt/CometDeath",10,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.88,1.12));
				A_StartSound("Celt/CometDeath",11,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.84,1.16));
				A_StartSound("Celt/CometDeath",12,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.80,1.20));
			}
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 
			{
				A_SpawnItemEx("KXCeltIceParticle2",0,0,5,frandom(-15,15),frandom(-15,15),frandom(5,15),random(1,360));
				A_SpawnItemEx("KXCeltIceParticle2",0,0,5,frandom(-15,15),frandom(-15,15),frandom(5,15),random(1,360));
				A_SpawnItemEx("KXCeltIceParticle2",0,0,5,frandom(-15,15),frandom(-15,15),frandom(5,15),random(1,360));
			}
			CELT U 0 Bright A_NoBlocking();
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				if (random(1,2) <= 1) A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				if (random(1,4) <= 1) A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				if (random(1,8) <= 1) A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				if (random(1,16) <= 1) A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01);
			}
			#### ########## 1 Bright 
			{
				A_KillChildren("Massacre");
				if (random(1,32) <= 1) A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				A_Fadeout(0.01); 
			}
			#### # 0 Bright
			{
				A_WeaselDeath();
			}
			Stop;
	}
}

class WeaselIceBigShot : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 5; // 3;
		Height 5; // 3;
		Scale 1.67;
		Speed 28; // 20;
		Damage 12; // 8;
		Projectile;
		RenderStyle "Add";
		DamageType "Ice";
		SeeSound "Celt/IceShot";
		DeathSound "Celt/IceHit";
		Translation "0:255=%[0.00,0.00,1.84]:[1.24,1.24,2.00]";
		Decal "RevenantScorch";
	}
	
	States
	{
		Spawn:
			IBAL AABB 2 Bright A_SpawnItemEx("WeaselIceBigShotTrail",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
			Loop;
		Death:
			IBAL AAAAAAAAAA 0 A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			IBAL DEFGHI 4 Bright;
			Stop;
	}
}

class WeaselIceBigShotTrail : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 2; // 1;
		Height 2; // 1;
		Speed 0;
		Damage 0;
		PROJECTILE;
		RenderStyle "Add";
		Translation "0:255=%[0.00,0.00,1.84]:[1.24,1.24,2.00]";
		+ClientSideOnly;
		+Randomize;
		Alpha 0.9;
		DamageType "Ice";
	}
	
	States
	{
		Spawn:
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL A 1 Bright A_FadeOut(0.04);
			IBAL A 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			IBAL B 1 Bright A_FadeOut(0.04);
			IBAL B 0 A_SetScale(scale.x-0.03);
			Loop;
	}
}

class WeaselDiamondDust : KCProjectile
{
	default
	{
		Tag "Diamond Dust";
		Radius 19; // 13;
		Height 11; // 8;
		Scale 1.34;
		Speed 30; // 25;
		Damage 0; // 0;
		Projectile;
		SeeSound "CELT/comet";
		Translation "0:255=%[0.00,0.00,2.00]:[2.00,2.00,2.00]";
		RenderStyle "Add";
		Projectile;
		Decal "RevenantScorch";
		DamageType "Ice";
	}
	
	States
	{
		Spawn:
			ICOM AAAABBBBCCCC 1 Bright A_SpawnItemEx("WeaselDiamondDustTail", 0, 0, 0, 0, 0, 0, 0, 128);
			Loop;
		Death:
			ICOM A 0 
			{
				A_StartSound("Celt/CometDeath",7,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(1.0,1.0));
				A_StartSound("Celt/CometDeath",8,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.95,1.05));
				A_StartSound("Celt/CometDeath",9,CHANF_DEFAULT,1.0,ATTN_NONE,frandom(0.9,1.1));
			}
			ICOM A 0 Bright 
			{
				A_Explode(480,320,0);
			}
			ICOM AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 
			{
				A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				if (random(1,4) <= 2) A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			}
			ICOM DDDEEEFFFGGGHHHIII 1 Bright 
			{
				A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
				if (random(1,4) <= 2) A_SpawnItemEx("WeaselRealDiamondDust",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10),random(1,360));
			}
			Stop;
	}
}

class WeaselDiamondDustTail : KCProjectile
{
	default
	{
		Tag "Diamond Dust";
		Radius 2; // 1;
		Height 2; // 1;
		Speed 0;
		Damage 0;
		RenderStyle "Add";
		Projectile;
		+DontSplash;
		+ClientSideOnly;
		DamageType "Ice";
	}
	
	States
	{
		Spawn:
			TNT1 A 2;
			IRTB ABCDEFGHI 1 Bright;
			Stop;
	}
}

class WeaselRealDiamondDust : KCProjectile
{
	default
	{
		Tag "Diamond Dust";
		Radius 18; // 15;
		Height 10; // 8;
		Speed 28; // 20;
		Damage 5; // 2;
		Scale 1.25;
		Projectile;
		+Ripper;
		BounceType "Hexen";
		Obituary "%o was chilled to the bone by the Ice Weasel's incredible frozen might";
		DamageType "Ice";
	}
	
	States
	{
		Spawn: 
			IRME ABCDEFGHIJKLMNS 2 Bright;
			IRME S 1 A_FadeOut(0.01);
			Wait;
	}
}

class WeaselIceCloneSpawner : PlasmaBallNew
{
	default
	{
		RenderStyle "Normal";
		Radius 32; // 24;
		Height 2; // 1;
		Speed 13; // 9;
		BounceType "Hexen";
		Damage 0;
		SeeSound "";
		DeathSound "";
		Translation "0:255=%[0.00,0.00,2.00]:[2.00,2.00,2.00]";
		DamageType "Ice";
	}
	
	States
	{
		Spawn:
			CELT ZZZZZZZZZZZZZZZZZZZZZZZZZZZ 1 A_SpawnItemEx("KXCeltIceParticle", Random(24, 32), 0, 4, 0, 0, (Random(20, 35)*0.1), Random(0, 360), 128);
			//CELT ZZZZZZZZZZZZZZZZZZZZZZZZZZZ 1 A_SpawnItemEx("KXCeltIceParticle", Random(24, 32), 0, 4, 0, 0, (Random(20, 35)*0.1), Random(0, 360), 128);
			TNT1 A 0 A_Stop();
			TNT1 A 0 A_StartSound("misc/freeze",CHAN_AUTO,CHANF_DEFAULT,1.0);
			Goto Death;
		Death:
			CELT YYYXXXWWWVVVUUUTTTSSSRRR 1 A_SpawnItemEx("KXCeltIceParticle", Random(24, 32), 0, 4, 0, 0, (Random(20, 35)*0.1), Random(0, 360), 128);
			TNT1 A 0 A_StartSound("misc/freeze",CHAN_AUTO,CHANF_DEFAULT,1.0);
			TNT1 A 0 Bright 
			{
				bool spawned;
				actor mo;
				[spawned, mo] = A_SpawnItemEx("KXCelt",0,0,1,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_NOCHECKPOSITION);
				if (mo)
				{
					if (master) mo.master = master;
				}
			}
			Stop;
	}
}

class WeaselIceMiniShot : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 5; // 3;
		Height 5; // 3;
		Scale 1.67;
		Speed 45; // 35;
		Damage 7; // 3;
		Projectile;
		RenderStyle "Add";
		DamageType "Ice";
		SeeSound "Celt/IceShot";
		DeathSound "Celt/IceHit";
	}
	
	States
	{
		Spawn:
			IPRJ AAABBBCCC 1 Bright A_SpawnItemEx("WeaselIceMiniShotTrail",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
			Loop;
		Death:
			IPRJ AAA 0 A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-4,4),frandom(-4,4),frandom(-4,4),random(1,360));
			IPRJ DEFGH 3 Bright;
			Stop;
	}
}

class WeaselIceMiniShot2 : WeaselIceMiniShot
{
	default
	{
		Tag "Ice Shard";
		Radius 4; // 3;
		Height 4; // 3;
		Scale 1.34;
		Speed 18; // 12;
		Damage 5; // 3;
	}
	
	States
	{
		Spawn:
			IPRJ AAABBBCCC 1 Bright 
			{
				if (level.time % 3 == 1) A_SpawnItemEx("WeaselIceMiniShotTrail",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
			}
			Loop;
		Death:
			IPRJ AAA 0 A_SpawnItemEx("KXCeltIceParticle",0,0,0,frandom(-4,4),frandom(-4,4),frandom(-4,4),random(1,360));
			IPRJ DEFGH 3 Bright;
			Stop;
	}
}

class WeaselIceMiniShotTrail : KCProjectile
{
	default
	{
		Tag "Ice Shard";
		Radius 1;
		Height 1;
		Speed 0;
		Damage 0;
		PROJECTILE;
		RenderStyle "Add";
		+ClientSideOnly;
		+Randomize;
		Alpha 1.0;
	}
	States
	{
		Spawn:
			IPRJ AABBCC 1 Bright A_FadeOut(0.14);
			Stop;
	}
}
